blog/urls.py
from django.urls import path
from  . import views

# from django.conf import settings
# from django.conf.urls.static import static

app_name='blog'

urlpatterns = [


path('', views.index, name='home'),
path('articles/', views.BlogListView.as_view(), name='articles'),
path('student/', views.RegisterStudent.as_view(), name='student'),
path('gallery/', views.GalleryListView.as_view(), name='gallery'),
# path('documents/', views.DocumentListView.as_view(), name='documents'),
# path('members/', views.MemberListView.as_view(), name='members'),
path('works/',views.WorkListView.as_view(),name="works"),
path('search/', views.post_search, name='search'),

path('<int:year>/<int:month>/<slug:slug>', views.post_view, name='post'),
path('about/', views.about, name='about'),
path('reg_success/', views.RegSuccess.as_view(), name='reg_successview'),

]

blogsettings/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.shortcuts import reverse
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField
from django_extensions.db.fields import AutoSlugField, ModificationDateTimeField

# Create your models here.
districts = (
    ('alp', 'Alappuzha'),
    ('ekm', 'Ernakulam'),
    ('idk', 'Idukki'),
    ('knr', 'Kannur'),
    ('ksr', 'Kasaragod'),
    ('kol', 'Kollam'),
    ('ktm', 'Kottayam'),
    ('koz', 'Kozhikode'),
    ('mpm', 'Malappuram'),
    ('pkd', 'Palakkad'),
    ('ptm', 'Pathanamthitta'),
    ('tvm', 'Thiruvananthapuram'),
    ('tcr', 'Thrissur'),
    ('wnd', 'Wayanad'),
)
positions = (
    ('Director', 'Director'),
    ('Chairman', 'Chairman'),
    ('Associate Director', 'Associate Director'),
    ('Secretary', 'Secretary'),
    ('Treasurer', 'Treasurer'),
    ('Member', 'Member'),
)
wtypes = (
    ('Workshops', 'Workshops'),
    ('Conferences', 'Conferences'),
    ('Seminars', 'Seminars'),
)
categories = (
    ('Statitics', 'Statitics'),
    ('Probabilty', 'Probabilty'),
    ('Algebra', 'Relational Algebra'),
    ('Geometry', 'Geometry'),
)


class Post(models.Model):
    title = models.CharField(max_length=70)
    slug = AutoSlugField(populate_from='title', overwrite=True)
    tags = TaggableManager()
    post_date = models.DateField(auto_now_add=True)
    post_update = ModificationDateTimeField()
    short_desc = models.TextField(max_length=250)
    img = models.ImageField(upload_to='img', blank=True,null=True)
    status = models.BooleanField(default=True, verbose_name="Approve Post")
    body = RichTextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post', args=[self.post_date.year, self.post_date.month, self.slug])


class Document(models.Model):
    file = models.FileField('Document', upload_to='mydocs/')
    fname = models.CharField(max_length=70)
    status = models.BooleanField(default=True, verbose_name="Status")
    category = models.CharField(
        max_length=40,
        choices=categories,
    )


class Link(models.Model):
    linkname = models.CharField(max_length=1000)
    name = models.CharField(max_length=70)
    status = models.BooleanField(default=True, verbose_name="Status")


class Work(models.Model):
    title = models.CharField(max_length=70)
    venue = models.CharField(max_length=70)
    status = models.BooleanField(default=True, verbose_name="Status")
    district = models.CharField(
        max_length=40,
        choices=districts,
    )
    sdate = models.DateTimeField()
    info = models.TextField()
    fdate = models.DateField()
    wtype = models.CharField(
        max_length=40,
        choices=wtypes,
    )





class Student(models.Model):
    name = models.CharField(max_length=100)
    district = models.CharField(
        max_length=40,
        choices=districts,
    )
    phone = models.CharField(max_length=10)
    email = models.EmailField(max_length=70, blank=True)
    organisation = models.CharField(max_length=250, verbose_name="Organization / Institution")
    address = models.TextField()
    joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Member(models.Model):
    name = models.CharField(max_length=100)
    rank = models.IntegerField(default=100)
    district = models.CharField(
        max_length=40,
        choices=districts,
    )
    position = models.CharField(
        max_length=30,
        choices=positions,
    )
    invigilation = models.CharField(max_length=250, verbose_name="Invigilation ")
    phone = models.CharField(max_length=10,blank=True)
    email = models.EmailField(max_length=70, blank=True)
    organisation = models.CharField(max_length=250, verbose_name="Organization / Institution")
    department = models.CharField(max_length=250, verbose_name="Department ")
    address = models.TextField()
    status = models.BooleanField(default=True, verbose_name="Status")
    joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Gallery(models.Model):
    title = models.CharField(max_length=70,null=True,blank=True)
    img = models.ImageField(upload_to='gallery', default="download.jpeg")
    status = models.BooleanField(default=True, verbose_name="Approve")
    g_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from ckeditor.widgets import CKEditorWidget
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.views.generic.edit import FormView
from django.views.generic.base import TemplateView

from .models import Post,Student,Document,Member,Link,Work,Gallery
# Create your views here.
def index(request):
    return render(request,'blog/home.html')

class BlogListView(ListView):
    model = Post
    template_name = "blog/articles.html"
    paginate_by = 10
    context_object_name = 'posts'
    queryset = Post.objects.filter(status=True)
    ordering = ['-post_update',]


class MemberListView(ListView):
    model = Member
    template_name = "blog/members.html"
    context_object_name = 'members'
    queryset = Member.objects.filter(status=True)
    ordering = ['rank',]

class DocumentListView(ListView):
    model = Document
    template_name = "blog/document.html"
    context_object_name = 'docs'
    queryset = Document.objects.filter(status=True)

class GalleryListView(ListView):
    model = Gallery
    template_name = "blog/gallery.html"
    context_object_name = 'galleries'
    queryset = Gallery.objects.filter(status=True)
    ordering = ['-g_date',]

class WorkListView(ListView):
    model = Work
    template_name = "blog/works.html"
    context_object_name = 'works'

def about(request):
    template = "blog/about.html"
    return render(request,template)
class test(TemplateView):
    template_name = 'base2.html'

def post_view(request, year, month, slug):
    template = 'blog/post.html'
    post = get_object_or_404(Post, post_date__year=year,
                             post_date__month=month, slug=slug)
    context = {'post': post}
    return render(request,'blog/post.html',context)

class RegisterStudent(CreateView):
    model = Student
    fields = ['name', 'district', 'phone','email', 'organisation', 'address']
    success_url = '/reg_success'

class RegSuccess(TemplateView):
    template_name = "blog/reg_success.html"

def post_search(request):
    query = request.GET.get('q')
    results = Post.objects.filter(title__icontains=query)
    context = {'posts': results, 'query': query}

    return render(request, 'blog/search.html', context)

blog/templates/base2.html
<!DOCTYPE html>
{% load static %}
<!--
  Theme Name: Enlight
  Theme URL: https://probootstrap.com/enlight-free-education-responsive-bootstrap-website-template
  Author: ProBootstrap.com
  Author URL: https://probootstrap.com
  License: Released for free under the Creative Commons Attribution 3.0 license (probootstrap.com/license)
-->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Trivan Tech_home</title>
    <meta name="description" content="The Institute of Mathematics Research and Train- ) is aimed at organizing workshops in collabo- IMRT ing( ration with colleges offering M.Sc. programme in Mathematics for improving mathematic">
    <meta name="keywords" content="The Institute of Mathematics Research and Train">

    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,700|Open+Sans" rel="stylesheet">

    <link rel="stylesheet" href="{%  static 'css/styles-merged.css'%}">
    <link rel="stylesheet" href="{%  static 'css/style.min.css'%}">
    <link rel="stylesheet" href="{%  static 'css/custom.css'%}">
{#           <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">#}

      <style>
          @font-face {
  font-family: 'icomoon';
  src:  url('{% static  'fonts/icomoon.eot'%}');
  src:  url('{% static  'fonts/icomoon.eot' %}') format('embedded-opentype'),
    url('{% static  'fonts/icomoon.ttf' %}') format('truetype'),
    url('{% static  'fonts/icomoon.woff' %}') format('woff'),
    url('{% static  'fonts/icomoon.svg' %}') format('svg');
  font-weight: normal;
  font-style: normal;
}
      </style>



  </head>
  <body>

    <div class="probootstrap-search" id="probootstrap-search">
      <a href="#" class="probootstrap-close js-probootstrap-close"><i class="icon-cross"></i></a>
      <form action="/search">
        <input type="search" name="q" id="search" placeholder="Search a keyword and hit enter...">
      </form>
    </div>

    <div class="probootstrap-page-wrapper">
      <!-- Fixed navbar -->

      <div class="probootstrap-header-top">
        <div class="container">
          <div class="row">
            <div class="col-lg-9 col-md-9 col-sm-9 probootstrap-top-quick-contact-info">
              <span><i class="icon-location2"></i>Karyvattom Campus,Thiruvanathapuram</span>
              <span><i class="icon-phone2"></i>+91-8089804597</span>
              <span><i class="icon-mail"></i>trivantech@gmail.com</span>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3 probootstrap-top-social">
              <ul>
                <li><a href="#"><i class="icon-twitter"></i></a></li>
                <li><a href="#"><i class="icon-facebook2"></i></a></li>
                <li><a href="#"><i class="icon-instagram2"></i></a></li>
                <li><a href="#"><i class="icon-youtube"></i></a></li>
                <li><a href="#" class="probootstrap-search-icon js-probootstrap-search"><i class="icon-search"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <nav class="navbar navbar-default probootstrap-navbar">
        <div class="container">
          <div class="navbar-header">
            <div class="btn-more js-btn-more visible-xs">
              <a href="#"><i class="icon-dots-three-vertical "></i></a>
            </div>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
              <a href="/" >   <img src="{% static 'image/logo.png' %}"  class="icon1" width=160px height=80px></a>

{#            <a class="navbar-brand" href="/" title="imrtkerala.com" style="background: url({% static 'images/logo.png' %}) no-repeat left 50% ;">rdsfgdgd</a>#}


          </div>

          <div id="navbar-collapse" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="{% url 'blog:home' %}">Home</a></li>
              <li><a href="{% url 'blog:articles' %}">Articles</a></li>
{#              <li><a href="{% url 'blog:members' %}">Members</a></li>#}
{#              <li><a href="{% url 'blog:documents' %}">Documents</a></li>#}
              <li><a href="{% url 'blog:gallery' %}">Gallery</a></li>
              <li><a href="{% url 'blog:works' %}">Workshops</a></li>

  <li><a href="{% url 'blog:student' %}">Register</a></li>
            </ul>
          </div>
        </div>
      </nav>

        {% block main %}
            {% endblock %}

      <section class="probootstrap-cta">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <h2 class="probootstrap-animate" data-animate-effect="fadeInRight">Get your Registration Now!</h2>
              <a href="{% url 'blog:student' %}" role="button" class="btn btn-primary btn-lg btn-ghost probootstrap-animate" data-animate-effect="fadeInLeft">Register</a>
            </div>
          </div>
        </div>
      </section>
      <footer class="probootstrap-footer probootstrap-bg">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <div class="probootstrap-footer-widget">
                <h3>About The Trivan Tech</h3>
                <p>We strive to be the leading provider of technical information, community
services, and personalised support to the world’s computer science and
technology communities, as well as to recognise the contributions of computer
science and engineering professionals, who develop new technologies and
applications to improve the lives of people everywhere. We are forging and
implementing forward-looking policies for creating a vibrant ecosystem that
primarily ideate growth of innovation and technology towards a sustainable living
world.</p>
                <h3>Social</h3>
                <ul class="probootstrap-footer-social">
                  <li><a href="#"><i class="icon-twitter"></i></a></li>
                  <li><a href="#"><i class="icon-facebook"></i></a></li>
                  <li><a href="#"><i class="icon-github"></i></a></li>
                  <li><a href="#"><i class="icon-dribbble"></i></a></li>
                  <li><a href="#"><i class="icon-linkedin"></i></a></li>
                  <li><a href="#"><i class="icon-youtube"></i></a></li>
                </ul>
              </div>
            </div>
            <div class="col-md-3 col-md-push-1">
              <div class="probootstrap-footer-widget">
                <h3>Links</h3>
                <ul>
                  <li><a href="#">Home</a></li>
                  <li><a href="#">Courses</a></li>
                  <li><a href="#">Teachers</a></li>
                  <li><a href="#">News</a></li>
                  <li><a href="#">Contact</a></li>
                </ul>
              </div>
            </div>
            <div class="col-md-4">
              <div class="probootstrap-footer-widget">
                <h3>Contact Info</h3>
                <ul class="probootstrap-contact-info">
                  <li><i class="icon-location2"></i> <span>Thiruvananthapuram</span></li>
                  <li><i class="icon-mail"></i><span>trivantech@gmail.com</span></li>
                  <li><i class="icon-phone2"></i><span>+91-8089084597</span></li>
                </ul>
              </div>
            </div>

          </div>
          <!-- END row -->

        </div>

        <div class="probootstrap-copyright">
          <div class="container">
            <div class="row">
              <div class="col-md-8 text-left">
                <p>&copy; All Rights Reserved. Designed &amp; Developed <i class="icon icon-heart"></i> by <a href="#">Trivan Tech Solutions</a></p>
              </div>
              <div class="col-md-4 probootstrap-back-to-top">
                <p><a href="#" class="js-backtotop">Back to top <i class="icon-arrow-long-up"></i></a></p>
              </div>
            </div>
          </div>
        </div>
      </footer>

    </div>
    <!-- END wrapper -->


    <script src="{% static 'js/scripts.min.js' %}"></script>
    <script src="{% static 'js/main.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>

  </body>
</html>

blog/templates/blog/about.html
{% extends 'base2.html' %}
{% load static %}
{% block main %}
 <section class="probootstrap-section probootstrap-section-colored">
        <div class="container">
          <div class="row">
            <div class="col-md-12 text-left section-heading probootstrap-animate mb0">
              <h1 class="mb0">About IMRT</h1>
            </div>
          </div>
        </div>
      </section>
{#    <section class="probootstrap-section probootstrap-bg-white">#}
{#      <div class="container">#}
{#          The Institute of Mathematics Research and Training(IMRT) is aimed at encouraging and promoting#}
{##}
{#facilities for fundamental research in the various branches of mathematical sciences including pure math-#}
{#ematics, applied mathematics, statistics, computer sciences, information technology, theoretical physics#}
{##}
{#and other related sciences. IMRT also envisages#}
{#      </div>#}
{#    </section>#}
     <section class="probootstrap-section">
        <div class="container">
          <div class="row">
            <div class="col-md-6 col-md-offset-3 text-center section-heading probootstrap-animate">
              <h2> Institute of Mathematics Research and Training(IMRT)</h2>
              <p class="lead">We strive to be the leading provider of technical information, community
services, and personalised support to the world’s computer science and
technology communities, as well as to recognise the contributions of computer
science and engineering professionals, who develop new technologies and
applications to improve the lives of people everywhere. We are forging and
implementing forward-looking policies for creating a vibrant ecosystem that
primarily ideate growth of innovation and technology towards a sustainable living
world.</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="service left-icon probootstrap-animate">
                <div class="icon"><i class="icon-checkmark"></i></div>
                <div class="text">
                  <h3>Consectetur Adipisicing</h3>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto provident qui tempore natus quos quibusdam soluta at.</p>
                </div>
              </div>
              <div class="service left-icon probootstrap-animate">
                <div class="icon"><i class="icon-checkmark"></i></div>
                <div class="text">
                  <h3>Aliquid Dolorum Saepe</h3>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto provident qui tempore natus quos quibusdam soluta at.</p>
                </div>
              </div>
              <div class="service left-icon probootstrap-animate">
                <div class="icon"><i class="icon-checkmark"></i></div>
                <div class="text">
                  <h3>Eveniet Tempora Anisi</h3>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto provident qui tempore natus quos quibusdam soluta at.</p>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="service left-icon probootstrap-animate">
                <div class="icon"><i class="icon-checkmark"></i></div>
                <div class="text">
                  <h3>Laboriosam Quod Dignissimos</h3>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto provident qui tempore natus quos quibusdam soluta at.</p>
                </div>
              </div>

              <div class="service left-icon probootstrap-animate">
                <div class="icon"><i class="icon-checkmark"></i></div>
                <div class="text">
                  <h3>Asperiores Maxime Modi</h3>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto provident qui tempore natus quos quibusdam soluta at.</p>
                </div>
              </div>

              <div class="service left-icon probootstrap-animate">
                <div class="icon"><i class="icon-checkmark"></i></div>
                <div class="text">
                  <h3>Libero Maxime Molestiae</h3>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto provident qui tempore natus quos quibusdam soluta at.</p>
                </div>
              </div>

            </div>
          </div>
          <!-- END row -->
        </div>
      </section>
{% endblock %}

blog/templates/blog/articles.html
{% extends 'base2.html' %}
{% load static %}
{% block main %}
 <section class="probootstrap-section probootstrap-section-colored">
        <div class="container">
          <div class="row">
            <div class="col-md-12 text-left section-heading probootstrap-animate mb0">
              <h1 class="mb0">Our Articles</h1>
            </div>
          </div>
        </div>
      </section>
    <section class="probootstrap-section">
        <div class="container">
          <div class="row">

{% for post in posts %}
              <div class="col-md-6">
              <div class="probootstrap-service-2 probootstrap-animate">
                <div class="image">
                  <div class="image-bg">

                      {% if post.img %}
                          <img src="{{ post.img.url }}" alt="{{ post.img.url }}">
                      {% else %}
                          <img src="{% static 'images/download.png' %}">
                      {% endif %}

                  </div>
                </div>
                <div class="text">
                  <span class="probootstrap-meta"><i class="icon-calendar2"></i> {{ post.post_date }}</span>
                  <h3>{{ post.title }}</h3>
                    <p>{{ post.short_desc }}</p>
                  <p><a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read More..</a> </p>
                </div>
              </div>
            </div>
{% endfor %}


          </div>
        </div>

    </section>

{% endblock %}

blog/templates/blog/document.html
{% extends 'base2.html' %}
{% load bootstrap4 %}

{% block main %}
<section>
    <div>
        <div class="row">
           
            <section class="probootstrap-section probootstrap-section-colored">
        <div class="container">
          <div class="row">
            <div class="col-md-12 text-left section-heading probootstrap-animate mb0">
              <h1 class="mb0">DOCUMENT LIST</h1>
            </div>
          </div>
        </div>
      </section>

                <div class="col-md-7 col-md-push-1  probootstrap-animate" id="probootstrap-content">
     

        </div>

{% endblock %}

blog/templates/blog/gallery.html
{% extends 'base2.html' %}
{% load bootstrap4 %}

{% block main %}
<section>
    <div>
        <div class="row">
           
            <section class="probootstrap-section probootstrap-section-colored">
        <div class="container">
          <div class="row">
            <div class="col-md-12 text-left section-heading probootstrap-animate mb0">
              <h1 class="mb0">GALLERY</h1>
            </div>
          </div>
        </div>
      </section>

            <section class="probootstrap-section probootstrap-bg-white">
      <div class="container">

        <div class="row">
          <div class="col-md-12">
            <div class="portfolio-feed three-cols">
              <div class="grid-sizer"></div>
              <div class="gutter-sizer"></div>
              <div class="probootstrap-gallery">

            {% for gal in galleries %}
                <figure itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject" class="grid-item probootstrap-animate">
                  <a href="#" itemprop="contentUrl" data-size="1000x632">
                    <img src="{{ gal.img.url }}" itemprop="thumbnail" alt="{{ gal.title }}" />
                  </a>
</figure>
            {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
            </section>

{% endblock %}

blog/templates/blog/members.html
{% extends 'base2.html' %}
{% load bootstrap4 %}

{% block main %}
<section>
    <div>
        <div class="row">
           
            <section class="probootstrap-section probootstrap-section-colored">
        <div class="container">
          <div class="row">
            <div class="col-md-12 text-left section-heading probootstrap-animate mb0">
              <h1 class="mb0">MEMBERS LIST</h1>
            </div>
          </div>
        </div>
      </section>

                <div class="col-md-7 col-md-push-1  probootstrap-animate" id="probootstrap-content">
     <table class="table table-striped">
    <thead>
      <tr>
        <th>NAME</th>
        <th>ADDRESS</th>
        <th>POSTION</th>
      </tr>
    </thead>
    <tbody>
 {% for member in members %}

      <tr>
        <td>{{ member.name }}<br>{{ member.invigilation }}<br>{{ member.department }}<br>{{ member.organisation }}<br></td>
        <td>{{ member.address }}</td>
        <td>{{ member.position }}<br></td>
      </tr>

    </tbody>
         {% endfor %}
  </table>

        </div>
        </div>
    </div>
</section>

{% endblock %}

blog/templates/blog/post.html
{% extends 'base2.html' %}
{% load static %}
{% block main %}
 <section class="probootstrap-section probootstrap-section-colored">
        <div class="container">
          <div class="row">
            <div class="col-md-12 text-left section-heading probootstrap-animate mb0">
              <h1 class="mb0">{{ post.title }}</h1>
            </div>
          </div>
        </div>
      </section>
    <section class="probootstrap-section">
        <div class="container">
          <div class="row">
              posted by:{{ post.post_date }}
            <h2>Summary:<b> {{ post.short_desc }}</b></h2>

             {{ post.body|safe }}



          </div>
        </div>

    </section>

{% endblock %}

blog/templates/blog/reg_success.html
{% extends 'base2.html' %}
{% load bootstrap4 %}

{% block main %}

<h3>You have been registered successfully. Thank You.</h3>

{% endblock %}

blog/templates/blog/search.html
{% extends 'base2.html' %}
{% load static %}
{% block main %}
 <section class="probootstrap-section probootstrap-section-colored">
        <div class="container">
          <div class="row">
            <div class="col-md-12 text-left section-heading probootstrap-animate mb0">
              <h1 class="mb0">Search Results....</h1>
            </div>
          </div>
        </div>
      </section>
    <section class="probootstrap-section">
        <div class="container">
          <div class="row">
{% if posts %}
                <div class="container">
                    <h1 class="margin-top">Results Found... <span class="text-primary">
                            "{{ query|truncatechars:20 }}"</span></h1>
                        <hr>
                </div>


{% endif %}
    {% for post in posts %}
              <div class="col-md-6">
              <div class="probootstrap-service-2 probootstrap-animate">
                <div class="image">
                  <div class="image-bg">

                      {% if post.img %}
                          <img src="{{ post.img.url }}" alt="{{ post.img.url }}">
                      {% else %}
                          <img src="{% static 'images/download.png' %}">
                      {% endif %}

                  </div>
                </div>
                <div class="text">
                  <span class="probootstrap-meta"><i class="icon-calendar2"></i> {{ post.post_date }}</span>
                  <h3>{{ post.title }}</h3>
                    <p>{{ post.short_desc }}</p>
                  <p><a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read More..</a> </p>
                </div>
              </div>
            </div>
     {% empty %}
     <div class="margin-top"><h1>Sorry No Resultes Found<span class="text-primary">
                        "{{ query|truncatechars:30 }}"</span>
                    </h1>
                    </div>
                        <h2><a href="/">Back To Home</a></h2>
    {% endfor %}



          </div>
        </div>

    </section>

{% endblock %}

blog/templates/blog/student_form.html
{% extends 'base2.html' %}
{% load bootstrap4 %}

{% block main %}
<section>
    <div>
        <div class="row">
           
            <section class="probootstrap-section probootstrap-section-colored">
        <div class="container">
          <div class="row">
            <div class="col-md-12 text-left section-heading probootstrap-animate mb0">
              <h1 class="mb0">STUDENT REGISTRATION</h1>
            </div>
          </div>
        </div>
      </section>

                <div class="col-md-7 col-md-push-1  probootstrap-animate" id="probootstrap-content">
  <form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">
   Submit

  </button>
  {% endbuttons %}
  </form>

        </div>
</section>
<script>
    window.onload = function() {
        $("#id_phone").attr('type', 'number');
    }
</script>
{% endblock %}

blog/templates/blog/works.html
{% extends 'base2.html' %}
{% load bootstrap4 %}

{% block main %}
<section>
    <div>
        <div class="row">
           
            <section class="probootstrap-section probootstrap-section-colored">
        <div class="container">
          <div class="row">
            <div class="col-md-12 text-left section-heading probootstrap-animate mb0">
              <h1 class="mb0">WORKSHOPS CONDUCTED</h1>
            </div>
          </div>
        </div>
      </section>

                <div class="col-md-7 col-md-push-1  probootstrap-animate" id="probootstrap-content">
     

                 <table class="table table-hover">
    <thead>
      <tr>
        <th>NAME</th>
        <th>VENUE</th>
        <th>DATE</th>
        <th>End-DATE</th>
      </tr>
    </thead>
    <tbody>
 {% for work in works %}

      <tr>
        <td>{{ work.title }}</td>
        <td>{{ work.venue }}</td>
        <td>{{ work.sdate }}</td>
        <td>{{ work.fdate }}</td>
      </tr>

    </tbody>
         {% endfor %}
  </table>

        </div>

{% endblock %}